document.writeln("<footer>");
document.writeln("    <div class=\'zerogrid wrap-footer\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'bottom-social\'>");
document.writeln("                <a href=\'http://renkaigis.com\' target=\'_blank\'><i class=\'fa fa-rss\'></i></a>");
document.writeln("                <a href=\'http://blog.renkaigis.com\' target=\'_blank\'><i class=\'fa fa-coffee\'></i></a>");
document.writeln("                <a href=\'https://github.com/renkaigis\' target=\'_blank\'><i class=\'fa fa-github-alt\'></i></a>");
document.writeln("                <a href=\'http://resume.renkaigis.com\' target=\'_blank\'><i class=\'fa fa-heartbeat\'></i></a>");
document.writeln("                <a href=\'http://photo.renkaigis.com\' target=\'_blank\'><i class=\'fa fa-camera-retro\'></i></a>");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'copyright\'>");
document.writeln("            <a href=\'https://beian.miit.gov.cn/\' target=\'_blank\'");
document.writeln("                style=\'color: hotpink;font-size: 80%;font-weight: normal;\'>陕ICP备17015858号</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'copyright\'>");
document.writeln("            Copyright &copy; 2021. Kai & Ru All rights reserved.<a target=\'_blank\' href=\'http://renkaigis.com\'></a>");
document.writeln("        </div>");
document.writeln("</footer>");